# numpy聚合操作

In [3]:
import numpy as np

In [5]:
L = np.random.random(100)
L

array([0.2164984 , 0.85856383, 0.02502545, 0.82035061, 0.73314203,
       0.27612982, 0.33299082, 0.53620184, 0.16851017, 0.54641387,
       0.35016312, 0.5770675 , 0.183382  , 0.12827027, 0.20115613,
       0.65204866, 0.63473847, 0.19199757, 0.11434724, 0.97720496,
       0.22284987, 0.77192674, 0.17830399, 0.15596141, 0.78691849,
       0.49571673, 0.22711968, 0.58788745, 0.35337303, 0.10856594,
       0.25254205, 0.18062712, 0.35199969, 0.16263051, 0.54289513,
       0.47552783, 0.49421634, 0.9157089 , 0.27409696, 0.29607253,
       0.4172196 , 0.71132797, 0.50325706, 0.12267246, 0.71170508,
       0.69807716, 0.02026949, 0.52982773, 0.73455133, 0.67719549,
       0.80015817, 0.60700167, 0.92708601, 0.22497136, 0.18064099,
       0.11921832, 0.99731041, 0.89182779, 0.29147315, 0.78221474,
       0.60125008, 0.94183414, 0.99230074, 0.36138194, 0.78762585,
       0.67444343, 0.90571218, 0.28609763, 0.81373394, 0.69850174,
       0.52078748, 0.45533403, 0.99107938, 0.24445982, 0.94627

In [7]:
sum(L)

51.01675984332645

In [9]:
np.sum(L)

51.01675984332643

In [14]:
bigarr = np.random.rand(1000)
%timeit sum(bigarr)
%timeit np.sum(bigarr)

104 µs ± 1.34 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
3.84 µs ± 102 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
np.max(bigarr)

0.9998823122918128

In [18]:
M = np.arange(16).reshape(4,-1)
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
np.sum(M)

120

In [20]:
np.max(M)

15

In [21]:
np.sum(M,axis=1)

array([ 6, 22, 38, 54])

In [22]:
np.prod(M)

0

In [25]:
np.prod(M + 1)

2004189184

In [26]:
np.mean(M)

7.5

In [27]:
np.median(M)

7.5

In [28]:
v = np.array([1,1,2,2,10])
v

array([ 1,  1,  2,  2, 10])

In [29]:
np.mean(v)

3.2

In [30]:
np.median(v)

2.0

In [33]:
np.percentile(bigarr,q=50)

0.49740011126301603

In [34]:
np.percentile(bigarr,q=100)

0.9998823122918128

In [35]:
np.percentile(bigarr,q=0)

0.0007748007491680253

In [37]:
np.percentile(bigarr,q=25)

0.2352336812524028

In [38]:
np.percentile(bigarr,q=75)

0.7598539591456921

In [39]:
for percent in [0,25,50,75,100]:
    print(np.percentile(bigarr,percent))

0.0007748007491680253
0.2352336812524028
0.49740011126301603
0.7598539591456921
0.9998823122918128


In [40]:
np.var(bigarr)

0.08792822875043584

In [41]:
np.std(bigarr)

0.2965269443919656

In [42]:
u = np.random.normal(0,1,size=1000000)

In [44]:
np.mean(u)

0.000618769116568976

In [45]:
np.std(u)

1.0008340180298008

### 索引

In [46]:
np.min(u)

-5.237128678892233

In [47]:
np.argmin(u)

391403

In [48]:
u[391403]

-5.237128678892233

In [49]:
np.random.shuffle(L)

In [50]:
L

array([0.45533403, 0.8430988 , 0.50822534, 0.29607253, 0.99731041,
       0.18064099, 0.183382  , 0.61704266, 0.22497136, 0.61731612,
       0.18062712, 0.19199757, 0.16851017, 0.94183414, 0.81373394,
       0.67719549, 0.78762585, 0.17830399, 0.94627083, 0.47552783,
       0.49421634, 0.61106782, 0.54289513, 0.67444343, 0.73455133,
       0.24445982, 0.15596141, 0.35337303, 0.92708601, 0.28609763,
       0.98623354, 0.16263051, 0.12267246, 0.41626102, 0.60125008,
       0.27192021, 0.07387342, 0.11033897, 0.71132797, 0.29147315,
       0.9157089 , 0.08372054, 0.69850174, 0.2164984 , 0.35199969,
       0.14612028, 0.85437886, 0.41114014, 0.50325706, 0.02502545,
       0.5770675 , 0.81346266, 0.89182779, 0.66565126, 0.25254205,
       0.42034368, 0.80015817, 0.78691849, 0.91115327, 0.22284987,
       0.99230074, 0.10226017, 0.71170508, 0.90571218, 0.58788745,
       0.77466578, 0.78221474, 0.28605299, 0.73314203, 0.22711968,
       0.60700167, 0.20115613, 0.54641387, 0.99107938, 0.33299

In [65]:
np.sort(L)

array([0.02026949, 0.02502545, 0.07387342, 0.08372054, 0.10226017,
       0.10856594, 0.11033897, 0.11434724, 0.11921832, 0.12267246,
       0.12827027, 0.14612028, 0.15596141, 0.16263051, 0.16851017,
       0.17830399, 0.18062712, 0.18064099, 0.183382  , 0.19199757,
       0.20115613, 0.2164984 , 0.22284987, 0.22497136, 0.22711968,
       0.24445982, 0.25254205, 0.27192021, 0.27409696, 0.27612982,
       0.28605299, 0.28609763, 0.29147315, 0.29607253, 0.33299082,
       0.35016312, 0.35199969, 0.35337303, 0.35605221, 0.36138194,
       0.41114014, 0.41626102, 0.4172196 , 0.42034368, 0.45533403,
       0.47552783, 0.49421634, 0.49571673, 0.50325706, 0.50822534,
       0.52078748, 0.52982773, 0.53620184, 0.54289513, 0.54641387,
       0.5770675 , 0.58788745, 0.60125008, 0.60700167, 0.61106782,
       0.61704266, 0.61731612, 0.63473847, 0.65204866, 0.66565126,
       0.67444343, 0.67719549, 0.69807716, 0.69850174, 0.71132797,
       0.71170508, 0.73314203, 0.73455133, 0.76266688, 0.77192

In [62]:
v = np.random.randint(10,size=(4,4))
v

array([[0, 5, 6, 6],
       [7, 9, 6, 9],
       [6, 6, 9, 4],
       [9, 9, 7, 5]])

In [63]:
np.sort(v)

array([[0, 5, 6, 6],
       [6, 7, 9, 9],
       [4, 6, 6, 9],
       [5, 7, 9, 9]])

In [64]:
np.sort(v,axis = 0)

array([[0, 5, 6, 4],
       [6, 6, 6, 5],
       [7, 9, 7, 6],
       [9, 9, 9, 9]])

In [88]:
w = np.random.randint(1,10,size=10)
w

array([7, 8, 3, 2, 5, 6, 4, 4, 2, 1])

In [90]:
np.random.shuffle(w)
w

array([2, 3, 4, 8, 6, 2, 7, 1, 5, 4])

In [92]:
np.argsort(w)

array([7, 0, 5, 1, 2, 9, 8, 4, 6, 3], dtype=int64)

In [96]:
np.partition(w,5)

array([3, 2, 1, 2, 4, 4, 5, 6, 7, 8])

In [97]:
np.argpartition(w,5)

array([1, 0, 7, 5, 9, 2, 8, 4, 6, 3], dtype=int64)

In [99]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
np.argsort(M)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)