# numpy array

In [2]:
import numpy as np

In [4]:
np.__version__

'1.15.4'

In [6]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [8]:
L[3] = "Learning"
L

[0, 1, 2, 'Learning', 4, 100, 6, 7, 8, 9]

In [11]:
arr = np.array([i for i in range(10)])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr.dtype

dtype('int32')

In [13]:
arr[3] = 3.14
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2 = np.array([1,2,3.0])
arr2
arr2.dtype

dtype('float64')

# 其他创建array方法

In [4]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.zeros(shape=(3,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((3,5),fill_value = 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arange

In [17]:
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## linspace  终值点包含

In [20]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [21]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [23]:
np.random.randint(0,10)

2

In [24]:
np.random.randint(0,10,10)

array([1, 0, 9, 1, 0, 4, 0, 6, 3, 1])

In [25]:
np.random.randint(0,10,(3,5))

array([[8, 9, 0, 8, 1],
       [7, 6, 7, 5, 5],
       [0, 1, 8, 9, 2]])

In [36]:
np.random.seed(666)
np.random.randint(0,10,(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [37]:
np.random.seed(666)
np.random.randint(0,10,(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [38]:
np.random.random()

0.7315955468480113

In [39]:
np.random.random(10)

array([0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197,
       0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896])

In [40]:
np.random.random((3,5))

array([[0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259],
       [0.26832981, 0.75366384, 0.66673747, 0.87287954, 0.52109719],
       [0.75020425, 0.32940234, 0.29130197, 0.00103619, 0.6361797 ]])

### 正态分布的浮点数，均值为0 方差为1

In [43]:
np.random.normal()

1.2317486561462025

### 均值10 方差100

In [45]:
np.random.normal(10,100)

-17.084406682175242

### 均值0 方差1 3*5的矩阵

In [46]:
np.random.normal(0,1,(3,5))

array([[ 1.42024914, -0.98226439,  0.80976498,  1.85205227,  1.67819021],
       [-0.98076924,  0.47031082,  0.18226991, -0.84388249,  0.20996833],
       [ 0.22958666,  0.26307642,  2.16633222, -1.04887593, -1.84768442]])

###  np.random.normal? 
### help(np.random.no)
### 查函数或模块的文档